apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-cloud-devops-fernando
  labels:
    app: capstone-cloud-devops-fernando
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-cloud-devops-fernando
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-cloud-devops-fernando
    spec:
      containers:
        - image: ferto31/capstone-cloud-devops-fernando
          imagePullPolicy: Always
          name: capstone-cloud-devops-fernando
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-cloud-devops-fernando
  labels:
    app: capstone-cloud-devops-fernando
spec:
  type: LoadBalancer
  selector:
    app: capstone-cloud-devops-fernando
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
