apiVersion: v1
kind: Service
metadata:
  name: capstone-cloud-devops-fernando
  labels:
    app: capstone-cloud-devops-fernando
spec:
  type: LoadBalancer
  selector:
    app: capstone-cloud-devops-fernando
  ports:
    - port: 80
      targetPort: 80
